api_listen = "127.0.0.1:4200"

[default_model]
provider = "openai"
model = "meta-llama/llama-3.3-70b-instruct"
api_key_env = "OPENROUTER_API_KEY"

[memory]
decay_rate = 0.05

[provider_urls]
openai = "https://openrouter.ai/api/v1"

[[mcp_servers]]
name = "agentgs"
timeout_secs = 60

[mcp_servers.transport]
type = "stdio"
command = "cmd.exe"
args = ["/c", "D:\\openfangAgentGS\\mcp_server.bat"]

[[mcp_servers]]
name = "memory"
timeout_secs = 60

[mcp_servers.transport]
type = "stdio"
command = "cmd.exe"
args = ["/c", "D:\\openfangAgentGS\\hydra_mcp_server.bat"]